In [1]:
import os
import pandas as pd
import zipfile
import pyodbc
import requests
import io
from datetime import datetime, timedelta
import sqlalchemy

In [2]:
server = 'DARCCVWSQL19'
#server = 'DESKTOP-37ESKFT\SQLEXPRESS'
database = 'TAPI'
tabla_nc = 'Valores_Gen_Diario_Automatico'
tabla_c = 'Hist_Bk'
tabla_v = 'View_Test3_VG'

In [12]:
#SELEC * FROM Diario;

connection_string = f'DRIVER=ODBC Driver 17 for SQL Server;SERVER={server};DATABASE={database};Trusted_Connection=yes;'

# Conectar a la base de datos
connection = pyodbc.connect(connection_string)

# Crear un cursor para ejecutar consultas
cursor = connection.cursor()

# TODO: Crear acÃ¡ la tabla en la BBDD
#  Consulta SQL
query_nc = f"SELECT * FROM {tabla_nc} where FECHA >= '2024-03-01' and FECHA <= '2024-05-30';"

query_c = f"SELECT * FROM {tabla_c} where FECHA >= '2024-03-01' and FECHA <= '2024-04-30';"

query_v = f"SELECT * FROM {tabla_v} where FECHA >= '2024-03-01' and FECHA <= '2024-05-30';"
# Ejecutar la consulta
df_c = pd.read_sql(query_c, connection)
df_nc = pd.read_sql(query_nc, connection)
df_v = pd.read_sql(query_v, connection)

# Cerrar el cursor
cursor.close()

C:\Users\jadurian\AppData\Local\Temp\ipykernel_22556\1252906826.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_c = pd.read_sql(query_c, connection)
C:\Users\jadurian\AppData\Local\Temp\ipykernel_22556\1252906826.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_nc = pd.read_sql(query_nc, connection)
C:\Users\jadurian\AppData\Local\Temp\ipykernel_22556\1252906826.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v = pd.read_sql(query_v, connection)

In [4]:
df_nc.describe()

,index,HORA,ARL,PI_SOTR,ARL_ECON,ENERGIA,PRECIO_NODO,PR_REM_ENERGIA,POT_DISP,POT_OPE_CPO,...,POT_DISP_GAS,COSTO_406,REM_ADICIONAL,CFO,CGN,CGO,POT_DISP_R19,FACTOR_KM,ENERG_GEN_TRANSAC,ENERG_OPE_TRANSAC
count,103680.000000,103680.00000,103680.0,103680.000000,103677.0,103680.000000,103677.0,64949.000000,103680.000000,92881.000000,...,103680.000000,103677.000000,103680.0,5770.000000,69747.000000,97.0,92016.000000,92880.000000,2463.000000,2463.000000
mean,6134.084423,12.50000,1.0,48.342338,1.0,50.266951,7534.0,30658.791531,99.593377,62.337644,...,99.246002,15166.411184,0.0,99.915078,99.986953,100.0,103.921914,0.954296,103.658716,139.052346
std,3452.290748,6.92222,0.0,74.968726,0.0,72.077004,0.0,30015.008728,89.720268,87.669042,...,89.832288,26247.116987,0.0,2.131424,0.989131,0.0,94.225238,0.189790,33.643972,53.537157
min,0.000000,1.00000,1.0,0.000000,1.0,0.000000,7534.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,10.000000,5.000000,100.0,0.000000,0.000000,0.000000,0.000000
25%,2951.750000,6.75000,1.0,0.000000,1.0,0.000000,7534.0,7534.000000,16.730000,0.000000,...,16.730000,0.000000,0.0,100.000000,100.000000,100.0,16.681000,1.000000,70.121002,91.719997
50%,6041.000000,12.50000,1.0,0.000000,1.0,7.007500,7534.0,26552.340000,84.000000,4.579000,...,82.720001,2.000000,0.0,100.000000,100.000000,100.0,91.000000,1.000000,108.900002,141.106003
75%,9890.000000,18.25000,1.0,96.000000,1.0,95.254749,7534.0,35579.320000,170.687752,112.996002,...,170.455002,23473.600000,0.0,100.000000,100.000000,100.0,180.301250,1.000000,129.432999,169.916000
max,11543.000000,24.00000,1.0,301.000000,1.0,285.308014,7534.0,926296.930000,296.670013,296.670013,...,381.897003,926296.930000,0.0,100.000000,100.000000,100.0,381.897000,1.000000,178.001999,313.588013

In [5]:
df_c.describe()

,index,HORA,ARL,PI_SOTR,ARL_ECON,ENERGIA,PRECIO_NODO,PR_REM_ENERGIA,POT_DISP,POT_OPE_CPO,...,COSTO_406,REM_ADICIONAL,CFO,CGN,POT_DISP_R19,FACTOR_KM,PGENE_RES354,CGU_PROPIO,CGU_MEM,CGU_GAS_CEDIDO
count,69120.000000,69120.000000,69120.0,69120.000000,69120.0,69120.000000,69120.0,4.068400e+04,69120.000000,61920.000000,...,6.912000e+04,69120.0,46.0,50354.0,61920.000000,61920.000000,4320.000000,4320.000000,4320.000000,4320.000000
mean,6293.426881,12.500000,1.0,43.749546,1.0,45.889361,7534.0,2.320251e+04,97.486699,56.253464,...,9.602908e+03,0.0,100.0,100.0,101.515685,0.937775,57.469660,7620.846106,25093.146333,8524.144012
std,3413.724290,6.922237,0.0,71.655313,0.0,68.935066,0.0,3.583965e+04,88.572502,82.983459,...,2.745706e+04,0.0,0.0,0.0,93.142238,0.219237,76.425254,9910.700619,10601.163154,10684.112590
min,304.000000,1.000000,1.0,0.000000,1.0,0.000000,7534.0,0.000000e+00,0.000000,0.000000,...,0.000000e+00,0.0,100.0,100.0,0.000000,0.000000,0.000000,0.000000,7534.000000,0.000000
25%,3683.750000,6.750000,1.0,0.000000,1.0,0.000000,7534.0,2.240000e+03,16.730000,0.000000,...,0.000000e+00,0.0,100.0,100.0,16.670000,1.000000,0.000000,0.000000,21276.822500,0.000000
50%,6095.500000,12.500000,1.0,0.000000,1.0,3.257000,7534.0,2.331492e+04,72.000000,0.000000,...,2.000000e+00,0.0,100.0,100.0,89.020000,1.000000,8.479000,2562.000000,24334.130000,2562.000000
75%,9915.250000,18.250000,1.0,84.000000,1.0,84.700998,7534.0,3.198164e+04,166.910503,107.199997,...,2.223198e+04,0.0,100.0,100.0,173.355750,1.000000,163.221750,21207.582500,30793.690000,21523.252500
max,11543.000000,24.000000,1.0,270.000000,1.0,266.519989,7534.0,5.267393e+06,296.670013,276.730011,...,5.267393e+06,0.0,100.0,100.0,381.897000,1.000000,168.000000,35462.760000,149154.520000,35462.760000

In [6]:
df_v.describe()

,index,HORA,ARL,PI_SOTR,ARL_ECON,ENERGIA,PRECIO_NODO,PR_REM_ENERGIA,POT_DISP,POT_OPE_CPO,...,CGN,CGO,POT_DISP_R19,FACTOR_KM,ENERG_GEN_TRANSAC,ENERG_OPE_TRANSAC,PGENE_RES354,CGU_PROPIO,CGU_MEM,CGU_GAS_CEDIDO
count,103680.000000,103680.00000,103680.0,103680.000000,103677.0,103680.000000,103677.0,6.494800e+04,103680.000000,92881.000000,...,69747.000000,97.0,92016.000000,92880.000000,2465.000000,2465.000000,4320.000000,4320.000000,4320.000000,4320.000000
mean,6136.520824,12.50000,1.0,48.342338,1.0,50.236938,7534.0,3.091448e+04,99.871492,62.365756,...,99.986953,100.0,104.217088,0.951607,103.590142,139.007707,57.469660,7620.846106,25093.146333,8524.144012
std,3456.783232,6.92222,0.0,74.968726,0.0,72.029219,0.0,3.765312e+04,89.872491,87.734528,...,0.989131,0.0,94.363515,0.194583,33.720747,53.559824,76.425254,9910.700619,10601.163154,10684.112590
min,0.000000,1.00000,1.0,0.000000,1.0,0.000000,7534.0,0.000000e+00,0.000000,0.000000,...,5.000000,100.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7534.000000,0.000000
25%,2951.750000,6.75000,1.0,0.000000,1.0,0.000000,7534.0,7.534000e+03,16.730000,0.000000,...,100.000000,100.0,16.676000,1.000000,70.120000,91.731000,0.000000,0.000000,21276.822500,0.000000
50%,6041.000000,12.50000,1.0,0.000000,1.0,6.929500,7534.0,2.752630e+04,84.500000,4.604000,...,100.000000,100.0,91.000000,1.000000,108.900000,141.060000,8.479000,2562.000000,24334.130000,2562.000000
75%,9897.000000,18.25000,1.0,96.000000,1.0,95.279999,7534.0,3.564755e+04,171.100006,113.000000,...,100.000000,100.0,181.003500,1.000000,129.433000,169.906006,163.221750,21207.582500,30793.690000,21523.252500
max,11543.000000,24.00000,1.0,301.000000,1.0,285.308014,7534.0,5.267393e+06,296.670013,296.670013,...,100.000000,100.0,381.897000,1.000000,178.001999,313.588013,168.000000,35462.760000,149154.520000,35462.760000

In [ ]:
df_v[(df_v['FECHA'] >= '2024-03-01') & (df_v['FECHA'] <= '2024-05-30')]

In [ ]:
df_nc

In [8]:
fecha_inicio_1 = '2024-03-01'
fecha_fin_1 = '2024-04-30'

fecha_inicio_2 = '2024-03-01'
fecha_fin_2 = '2024-05-30'

In [9]:
df_c_filtered = df_c[(df_c['FECHA'] >= fecha_inicio_1) & (df_c['FECHA'] <= fecha_fin_1)]
df_v_filtered_1 = df_v[(df_v['FECHA'] >= fecha_inicio_1) & (df_v['FECHA'] <= fecha_fin_1)]

df_nc_filtered = df_nc[(df_nc['FECHA'] >= fecha_inicio_2) & (df_nc['FECHA'] <= fecha_fin_2)]
df_v_filtered_2 = df_v[(df_v['FECHA'] >= fecha_inicio_2) & (df_v['FECHA'] <= fecha_fin_2)]

In [10]:
comparacion_c_v = df_c_filtered.equals(df_v_filtered_1)
comparacion_nc_v = df_nc_filtered.equals(df_v_filtered_2)

In [11]:
print(f"ComparaciÃ³n entre df_c y df_v entre {fecha_inicio_1} y {fecha_fin_1}: {'Iguales' if comparacion_c_v else 'Diferentes'}")
print(f"ComparaciÃ³n entre df_nc y df_v entre {fecha_inicio_2} y {fecha_fin_2}: {'Iguales' if comparacion_nc_v else 'Diferentes'}")

ComparaciÃ³n entre df_c y df_v entre 2024-03-01 y 2024-04-30: Diferentes
ComparaciÃ³n entre df_nc y df_v entre 2024-03-01 y 2024-05-30: Diferentes