Notebook para analizar las diferencias entre el reporte post operativo mensual vs el diario

In [1]:
#Librerias

import pandas as pd

In [2]:
df_m = pd.read_excel(r"Datos\VALORES_GENERADORES mensual.xlsx")

In [17]:
df_m.info(verbose=True, max_cols=100)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505920 entries, 0 to 505919
Data columns (total 33 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   FECHA                505920 non-null  datetime64[ns]
 1   HORA                 505920 non-null  int64
 2   GRUPO                505920 non-null  object
 3   ARL_ECON             505920 non-null  int64
 4   EST_REMUN            505920 non-null  object
 5   SMEC                 505920 non-null  object
 6   ENERGIA              505920 non-null  float64
 7   POT_DISP             505920 non-null  float64
 8   ENERG_OPERADA        420144 non-null  float64
 9   POT_RECONOC          505776 non-null  float64
 10  POT_DISP_GN          505920 non-null  float64
 11  PIND                 421848 non-null  float64
 12  PINDFORZ             421848 non-null  float64
 13  PRECIO_NODO          505920 non-null  int64
 14  PR_REM_ENERGIA       274717 non-null  float64
 15  SCTD                 261174 non-null  float64
 16  SCO                  241074 non-null  float64
 17  REM_ADICIONAL        505920 non-null  int64
 18  COSTO_406            500526 non-null  float64
 19  COMPRA_SPOT          481728 non-null  float64
 20  DESP_ECON            505920 non-null  object
 21  REMUN_ADIC_6866      0 non-null       float64
 22  POT_DISP_R19         421104 non-null  float64
 23  CGU_COMPR_OPT        0 non-null       float64
 24  HORA_REPRESENTATIVA  105133 non-null  object
 25  FACTOR_KM            421104 non-null  float64
 26  PGENE_RES354         8184 non-null    float64
 27  SOBREC_FORZ_PROPIO   2439 non-null    float64
 28  CGU_PROPIO           8184 non-null    float64
 29  CGU_MEM              8184 non-null    float64
 30  CGU_GAS_CEDIDO       8184 non-null    float64
 31  ENERG_GEN_TRANSAC    9105 non-null    float64
 32  ENERG_OPE_TRANSAC    9105 non-null    float64
dtypes: datetime64[ns](1), float64(23), int64(4), object(5)
memory usage: 127.4+ MB

In [2]:
df_d = pd.read_excel(r"Datos\VALORES_GENERADORES Diario.xlsx")

In [4]:
df_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16320 entries, 0 to 16319
Data columns (total 39 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   GRUPO                16320 non-null  object
 1   HORA                 16320 non-null  int64
 2   ARL                  16320 non-null  int64
 3   ESTADO_OPE           16320 non-null  object
 4   PI_SOTR              16320 non-null  float64
 5   ARL_ECON             16320 non-null  int64
 6   EST_REMUN            16320 non-null  object
 7   ENERGIA              16320 non-null  float64
 8   PRECIO_NODO          16320 non-null  int64
 9   PR_REM_ENERGIA       8321 non-null   float64
 10  SMEC                 16320 non-null  object
 11  POT_DISP             16320 non-null  float64
 12  POT_OPE_CPO          13612 non-null  float64
 13  COMPRA_SPOT          14232 non-null  float64
 14  SCTD                 7654 non-null   float64
 15  SCO                  7006 non-null   float64
 16  PIND                 13608 non-null  float64
 17  PINDPROG             13608 non-null  float64
 18  PINDFORZ             13608 non-null  float64
 19  POT_DISP_GAS         16320 non-null  float64
 20  POT_DISP_RESERVA     0 non-null      float64
 21  GAS_NOMINADO         0 non-null      float64
 22  COSTO_406            16122 non-null  float64
 23  REM_ADICIONAL        16320 non-null  int64
 24  DESP_ECON            16320 non-null  object
 25  CCM                  96 non-null     float64
 26  CFO                  552 non-null    float64
 27  CGN                  5928 non-null   float64
 28  CGO                  2760 non-null   float64
 29  POT_DISP_R19         13584 non-null  float64
 30  FACTOR_KM            13584 non-null  float64
 31  HORA_REPRESENTATIVA  2871 non-null   object
 32  ENERG_GEN_TRANSAC    259 non-null    float64
 33  ENERG_OPE_TRANSAC    259 non-null    float64
 34  SOBREC_FORZ_PROPIO   72 non-null     float64
 35  PGENE_RES354         0 non-null      float64
 36  CGU_PROPIO           0 non-null      float64
 37  CGU_MEM              0 non-null      float64
 38  CGU_GAS_CEDIDO       0 non-null      float64
dtypes: float64(28), int64(5), object(6)
memory usage: 4.9+ MB

In [3]:
df_d.columns

Index(['GRUPO', 'HORA', 'ARL', 'ESTADO_OPE', 'PI_SOTR', 'ARL_ECON',
       'EST_REMUN', 'ENERGIA', 'PRECIO_NODO', 'PR_REM_ENERGIA', 'SMEC',
       'POT_DISP', 'POT_OPE_CPO', 'COMPRA_SPOT', 'SCTD', 'SCO', 'PIND',
       'PINDPROG', 'PINDFORZ', 'POT_DISP_GAS', 'POT_DISP_RESERVA',
       'GAS_NOMINADO', 'COSTO_406', 'REM_ADICIONAL', 'DESP_ECON', 'CCM', 'CFO',
       'CGN', 'CGO', 'POT_DISP_R19', 'FACTOR_KM', 'HORA_REPRESENTATIVA',
       'ENERG_GEN_TRANSAC', 'ENERG_OPE_TRANSAC', 'SOBREC_FORZ_PROPIO',
       'PGENE_RES354', 'CGU_PROPIO', 'CGU_MEM', 'CGU_GAS_CEDIDO'],
      dtype='object')

In [21]:
df_m.sort_index(axis=1).columns

Index(['ARL_ECON', 'CGU_COMPR_OPT', 'CGU_GAS_CEDIDO', 'CGU_MEM', 'CGU_PROPIO',
       'COMPRA_SPOT', 'COSTO_406', 'DESP_ECON', 'ENERGIA', 'ENERG_GEN_TRANSAC',
       'ENERG_OPERADA', 'ENERG_OPE_TRANSAC', 'EST_REMUN', 'FACTOR_KM', 'FECHA',
       'GRUPO', 'HORA', 'HORA_REPRESENTATIVA', 'PGENE_RES354', 'PIND',
       'PINDFORZ', 'POT_DISP', 'POT_DISP_GN', 'POT_DISP_R19', 'POT_RECONOC',
       'PRECIO_NODO', 'PR_REM_ENERGIA', 'REMUN_ADIC_6866', 'REM_ADICIONAL',
       'SCO', 'SCTD', 'SMEC', 'SOBREC_FORZ_PROPIO'],
      dtype='object')

In [11]:
df_m.head(1)

,FECHA,HORA,GRUPO,ARL_ECON,EST_REMUN,SMEC,ENERGIA,POT_DISP,ENERG_OPERADA,POT_RECONOC,...,CGU_COMPR_OPT,HORA_REPRESENTATIVA,FACTOR_KM,PGENE_RES354,SOBREC_FORZ_PROPIO,CGU_PROPIO,CGU_MEM,CGU_GAS_CEDIDO,ENERG_GEN_TRANSAC,ENERG_OPE_TRANSAC
0,2023-12-01,1,9JULDI01,1,lib,S,0.0,4.2,0.0,4.2,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
for i in df_d:
    print(i)

GRUPO
HORA
ARL
ESTADO_OPE
PI_SOTR
ARL_ECON
EST_REMUN
ENERGIA
PRECIO_NODO
PR_REM_ENERGIA
SMEC
POT_DISP
POT_OPE_CPO
COMPRA_SPOT
SCTD
SCO
PIND
PINDPROG
PINDFORZ
POT_DISP_GAS
POT_DISP_RESERVA
GAS_NOMINADO
COSTO_406
REM_ADICIONAL
DESP_ECON
CCM
CFO
CGN
CGO
POT_DISP_R19
FACTOR_KM
HORA_REPRESENTATIVA
ENERG_GEN_TRANSAC
ENERG_OPE_TRANSAC
SOBREC_FORZ_PROPIO
PGENE_RES354
CGU_PROPIO
CGU_MEM
CGU_GAS_CEDIDO

In [15]:
df_d.describe()

,HORA,ARL,PI_SOTR,ARL_ECON,ENERGIA,PRECIO_NODO,PR_REM_ENERGIA,POT_DISP,POT_OPE_CPO,COMPRA_SPOT,...,CGO,POT_DISP_R19,FACTOR_KM,ENERG_GEN_TRANSAC,ENERG_OPE_TRANSAC,SOBREC_FORZ_PROPIO,PGENE_RES354,CGU_PROPIO,CGU_MEM,CGU_GAS_CEDIDO
count,16320.000000,16320.0,16320.000000,16320.0,16320.000000,16320.0,8321.000000,16320.000000,13612.000000,14232.000000,...,2760.0,13584.000000,13584.000000,259.000000,259.000000,72.000000,0.0,0.0,0.0,0.0
mean,12.500000,1.0,19.115680,1.0,20.785057,3767.0,36037.582224,62.852210,27.438029,0.591335,...,100.0,79.549733,0.997928,85.154062,115.556830,2777.870000,NaN,NaN,NaN,NaN
std,6.922399,0.0,108.656324,0.0,100.315849,0.0,57085.252490,173.573025,122.332805,11.453399,...,0.0,213.254755,0.042607,45.499071,71.462529,948.661039,NaN,NaN,NaN,NaN
min,1.000000,1.0,0.000000,1.0,0.000000,3767.0,0.000000,0.000000,0.000000,0.000000,...,100.0,0.000000,0.000000,21.750000,21.750000,2111.740000,NaN,NaN,NaN,NaN
25%,6.750000,1.0,0.000000,1.0,0.000000,3767.0,0.000000,1.000000,0.000000,0.000000,...,100.0,1.000000,1.000000,36.664000,43.884500,2111.740000,NaN,NaN,NaN,NaN
50%,12.500000,1.0,0.000000,1.0,0.000000,3767.0,21327.940000,15.000000,0.000000,0.000000,...,100.0,14.000000,1.000000,76.474000,95.367000,2111.740000,NaN,NaN,NaN,NaN
75%,18.250000,1.0,0.000000,1.0,2.570000,3767.0,47814.220000,50.000000,0.696000,0.050000,...,100.0,50.000000,1.000000,114.523000,154.981000,4110.130000,NaN,NaN,NaN,NaN
max,24.000000,1.0,2639.100000,1.0,2395.790000,3767.0,482386.900000,2650.500000,2420.946000,384.272000,...,100.0,2945.000000,1.000000,181.512000,273.620000,4110.130000,NaN,NaN,NaN,NaN